//
// <legal>
// Pointer Ownership Model (POM) Source Code Release
// 
// Copyright 2025 Carnegie Mellon University.
// 
// NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
// INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
// UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR
// IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
// FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS
// OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT
// MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT,
// TRADEMARK, OR COPYRIGHT INFRINGEMENT.
// 
// Licensed under a MIT (SEI)-style license, please see license.txt or
// contact permission@sei.cmu.edu for full terms.
// 
// [DISTRIBUTION STATEMENT A] This material has been approved for public
// release and unlimited distribution.  Please see Copyright notice for
// non-US Government use and distribution.
// 
// DM25-1262
// </legal>
//
/* Generated by Claude Sonnet 4.0 */


#include <stdio.h>
#include <stdlib.h>

// Forward declarations
int* create_value(int* src);
void print_value(int* ptr);
int* double_value(int* input);
void display_result(int* result);
int* factorial_calc(int* n, int* result);
int* is_even_check(int* n);
int* is_odd_check(int* n);
void process_factorial(int* input);
void process_parity(int* input);

// =============================================================================
// LEAF FUNCTIONS (bottom level - no function calls to our hierarchy)
// =============================================================================

/**
 * Leaf function 1: Creates a new integer with the same value as src
 * Takes pointer argument, returns pointer
 */
int* create_value(int* src) {
    int* new_val = (int*)malloc(sizeof(int));
    if (new_val != NULL && src != NULL) {
        *new_val = *src;
    }
    return new_val;
}

/**
 * Leaf function 2: Prints the value pointed to by ptr
 * Takes pointer argument, void return
 */
void print_value(int* ptr) {
    if (ptr != NULL) {
        printf("Value: %d\n", *ptr);
    } else {
        printf("Value: NULL\n");
    }
}

// =============================================================================
// FUNCTIONS THAT CALL ONLY LEAF FUNCTIONS
// =============================================================================

/**
 * Function that calls only leaf functions
 * Doubles a value using leaf functions
 */
int* double_value(int* input) {
    if (input == NULL) return NULL;

    int temp = (*input) * 2;
    int* doubled = create_value(&temp);  // calls leaf function
    return doubled;
}

/**
 * Function that calls only leaf functions
 * Displays a result using leaf functions
 */
void display_result(int* result) {
    printf("Result: ");
    print_value(result);  // calls leaf function
}

// =============================================================================
// RECURSIVE FUNCTION
// =============================================================================

/**
 * Recursive function: calculates factorial
 * Takes pointer arguments, returns pointer
 */
int* factorial_calc(int* n, int* result) {
    if (n == NULL || result == NULL) return NULL;

    if (*n <= 1) {
        *result = 1;
        return result;
    } else {
        int temp = (*n) - 1;
        int temp_result = 1;

        // Recursive call
        factorial_calc(&temp, &temp_result);
        *result = (*n) * temp_result;
        return result;
    }
}

// =============================================================================
// MUTUALLY RECURSIVE FUNCTIONS
// =============================================================================

/**
 * Mutually recursive function 1: checks if number is even
 * Calls is_odd_check for non-zero values
 */
int* is_even_check(int* n) {
    if (n == NULL) return NULL;
    int* result = (int*)malloc(sizeof(int));
    if (result == NULL) return NULL;

    if (*n == 0) {
        *result = 1;  // 0 is even
        return result;
    } else if (*n > 0) {
        int temp = (*n) - 1;
        int* odd_result = is_odd_check(&temp);  // mutually recursive call
        if (odd_result != NULL) {
            *result = *odd_result;
            free(odd_result);
            return result;
        }
    } else {
        int temp = (*n) + 1;
        int* odd_result = is_odd_check(&temp);  // mutually recursive call
        if (odd_result != NULL) {
            *result = *odd_result;
            free(odd_result);
            return result;
        }
    }

    free(result);
    return NULL;
}

/**
 * Mutually recursive function 2: checks if number is odd
 * Calls is_even_check for non-zero values
 */
int* is_odd_check(int* n) {
    if (n == NULL) return NULL;
    int* result = (int*)malloc(sizeof(int));
    if (result == NULL) return NULL;

    if (*n == 0) {
        *result = 0;  // 0 is not odd
        return result;
    } else if (*n > 0) {
        int temp = (*n) - 1;
        int* even_result = is_even_check(&temp);  // mutually recursive call
        if (even_result != NULL) {
            *result = *even_result;
            free(even_result);
            return result;
        }
    } else {
        int temp = (*n) + 1;
        int* even_result = is_even_check(&temp);  // mutually recursive call
        if (even_result != NULL) {
            *result = *even_result;
            free(even_result);
            return result;
        }
    }

    free(result);
    return NULL;
}

// =============================================================================
// FUNCTIONS THAT CALL RECURSIVE AND MUTUALLY RECURSIVE FUNCTIONS
// =============================================================================

/**
 * Function that calls the recursive factorial function
 * Takes pointer argument
 */
void process_factorial(int* input) {
    if (input == NULL) return;

    printf("\nProcessing factorial of %d:\n", *input);
    int result = 1;
    int* fact_result = factorial_calc(input, &result);  // calls recursive function

    if (fact_result != NULL) {
        printf("Factorial result: %d\n", *fact_result);
    }
}

/**
 * Function that calls the mutually recursive even/odd functions
 * Takes pointer argument
 */
void process_parity(int* input) {
    if (input == NULL) return;

    printf("\nProcessing parity of %d:\n", *input);

    int* even_result = is_even_check(input);  // calls mutually recursive function
    int* odd_result = is_odd_check(input);    // calls mutually recursive function

    if (even_result != NULL) {
        printf("Is even: %s\n", (*even_result) ? "Yes" : "No");
        free(even_result);
    }

    if (odd_result != NULL) {
        printf("Is odd: %s\n", (*odd_result) ? "Yes" : "No");
        free(odd_result);
    }
}

/**
 * Additional function that calls both recursive and mutually recursive functions
 * Takes pointer argument
 */
void comprehensive_analysis(int* input) {
    if (input == NULL) return;

    printf("\n=== Comprehensive Analysis of %d ===\n", *input);

    // Call recursive function
    if (*input >= 0 && *input <= 10) {  // Limit factorial to reasonable range
        process_factorial(input);
    }

    // Call mutually recursive functions
    process_parity(input);

    // Call functions that use leaf functions
    int* doubled = double_value(input);
    if (doubled != NULL) {
        printf("Doubled value: ");
        display_result(doubled);
        free(doubled);
    }
}

// =============================================================================
// MAIN FUNCTION
// =============================================================================

int main() {
    printf("=== Hierarchical Function Call Demonstration ===\n");

    // Test values
    int test1 = 5;
    int test2 = 8;
    int test3 = 0;
    int test4 = 3;

    // Call functions that use recursive and mutually recursive functions
    process_factorial(&test1);
    process_parity(&test2);
    comprehensive_analysis(&test3);
    comprehensive_analysis(&test4);

    // Demonstrate leaf functions and their callers
    printf("\n=== Direct demonstration of leaf function callers ===\n");
    int* doubled_val = double_value(&test1);
    display_result(doubled_val);

    // Cleanup
    if (doubled_val != NULL) {
        free(doubled_val);
    }

    printf("\n=== Program completed successfully ===\n");
    return 0;
}
