#!/usr/bin/env bash
# pom-lint
#
# <legal>
# Pointer Ownership Model (POM) Source Code Release
# 
# Copyright 2025 Carnegie Mellon University.
# 
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR
# IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
# FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS
# OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT
# MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT,
# TRADEMARK, OR COPYRIGHT INFRINGEMENT.
# 
# Licensed under a MIT (SEI)-style license, please see license.txt or
# contact permission@sei.cmu.edu for full terms.
# 
# [DISTRIBUTION STATEMENT A] This material has been approved for public
# release and unlimited distribution.  Please see Copyright notice for
# non-US Government use and distribution.
# 
# DM25-1262
# </legal>
#


POM_SCHEMA_FILE="/opt/pom/pom.yamale.yml"

# Check if arguments are passed
if [ $# -eq 0 ]; then
    echo "No arguments provided. Please provide a path to the POM YAML file."
    exit 1
fi

if [ -z "$1" ]; then
    echo "No argument provided. Please provide a path to the POM YAML file."
    exit 1
fi


# Check if the schema file exists
if [ ! -f "$POM_SCHEMA_FILE" ]; then
    echo "Schema file not found: $POM_SCHEMA_FILE"
    exit 1
fi

# Ensure the provided argument is a file
if [ ! -f "$1" ]; then
    echo "File not found: $1"
    exit 1
fi

# Verify yamale is installed
pip list | grep -qF yamale
yamale_found=$?

if [ $yamale_found -ne 0 ]; then
    echo "yamale not found, please install yamale with pip"
    exit 1
fi

# Run yamale to validate the POM YAML file
yamale -s $POM_SCHEMA_FILE $1
